DECLARE
    V_DEF_PERCENT VARCHAR2(30);
    V_PERCENT VARCHAR2(5);
BEGIN
    FOR EMP IN (
        SELECT 
            EM.MANAGER_ID,
            EM.FIRST_NAME||' '||EM.LAST_NAME AS EMP_NAME, 
            EM.COMMISSION_PCT*100 AS PERCENT_OF_SALARY
        FROM HR.EMPLOYEES EM
        WHERE EM.DEPARTMENT_ID=80
        ORDER BY EMP_NAME) 
    LOOP
        IF EMP.MANAGER_ID=100 THEN
            dbms_output.put_line('EMPLOYEE '||EMP.EMP_NAME||', SALARY % FORBIDDEN AT THIS TIME');
            CONTINUE;
        END IF;
        V_PERCENT:=CONCAT(EMP.PERCENT_OF_SALARY,'%');
        IF (EMP.PERCENT_OF_SALARY BETWEEN 10 AND 20) = TRUE THEN
            V_DEF_PERCENT:='MINIMUM';
        ELSIF (EMP.PERCENT_OF_SALARY BETWEEN 25 AND 30) = TRUE THEN
            V_DEF_PERCENT:='MIDDLE';
        ELSIF (EMP.PERCENT_OF_SALARY BETWEEN 35 AND 40) = TRUE THEN
            V_DEF_PERCENT:='MAXIMUM';
        END IF;
        dbms_output.put_line('EMPLOYEE '||EMP.EMP_NAME||'; SALARY % - '||V_PERCENT||'; ITS A - '||V_DEF_PERCENT);
    END LOOP;
END;
/

SELECT EM.MANAGER_ID, EM.FIRST_NAME||' '||EM.LAST_NAME AS EMP_NAME, EM.COMMISSION_PCT*100 AS PERCENT_OF_SALARY
FROM HR.EMPLOYEES EM
WHERE EM.DEPARTMENT_ID=80
ORDER BY 2
;
