CREATE OR REPLACE PACKAGE UTIL AS

    FUNCTION GET_JOB_TITLE(
        P_EMPLOYEE_ID IN NUMBER) 
    RETURN VARCHAR2;
    
    FUNCTION GET_DEP_NAME(
       P_EMPLOYEE_ID IN NUMBER) 
    RETURN VARCHAR2;
    
    PROCEDURE DEL_JOB(
        P_JOB_ID IN ANDREW.JOBS.JOB_ID%TYPE,
        PO_RESULT OUT VARCHAR2);
        
END UTIL;
/

CREATE OR REPLACE PACKAGE BODY UTIL AS

    FUNCTION GET_JOB_TITLE(P_EMPLOYEE_ID IN NUMBER) 
        RETURN VARCHAR2 IS
        V_JOB_TITLE JOBS.JOB_TITLE%TYPE;
    BEGIN
        SELECT J.JOB_TITLE
        INTO V_JOB_TITLE
        FROM EMPLOYEES EM
        JOIN JOBS J
        ON EM.JOB_ID = J.JOB_ID
        WHERE EM.EMPLOYEE_ID = P_EMPLOYEE_ID;
    RETURN V_JOB_TITLE;
    END GET_JOB_TITLE;
    
    FUNCTION GET_DEP_NAME(P_EMPLOYEE_ID IN NUMBER) 
        RETURN VARCHAR2 IS 
        V_DEPARTMENT_NAME ANDREW.DEPARTMENTS.DEPARTMENT_NAME%TYPE;
    BEGIN
        SELECT DEP.DEPARTMENT_NAME
        INTO V_DEPARTMENT_NAME
        FROM ANDREW.EMPLOYEES EM
        JOIN ANDREW.DEPARTMENTS DEP
        ON EM.DEPARTMENT_ID=DEP.DEPARTMENT_ID
        WHERE EMPLOYEE_ID=P_EMPLOYEE_ID;
    
        RETURN V_DEPARTMENT_NAME;
    END GET_DEP_NAME;
    
    PROCEDURE DEL_JOB(
        P_JOB_ID IN ANDREW.JOBS.JOB_ID%TYPE,
        PO_RESULT OUT VARCHAR2) IS
        V_IS_CREATED NUMBER;
    BEGIN
        SELECT TO_NUMBER(COUNT(J.JOB_ID))
        INTO V_IS_CREATED
        FROM ANDREW.JOBS J
        WHERE J.JOB_ID='AD_PRES';
        
        IF V_IS_CREATED=0 THEN
            PO_RESULT:=P_JOB_ID||' DOESNT CREATED';
        ELSE
            DELETE FROM ANDREW.JOBS J
            WHERE J.JOB_ID=P_JOB_ID;
            --COMMIT;
            PO_RESULT:=P_JOB_ID||' DELETED SUCCESFULLY';
        END IF;
    END DEL_JOB;

END UTIL;
/

DECLARE
    V_MESSAGE VARCHAR2(50);
    V_JOB_ID ANDREW.JOBS.JOB_ID%TYPE :='SOME';
BEGIN
    UTIL.DEL_JOB(P_JOB_ID=>V_JOB_ID,
            PO_RESULT=>V_MESSAGE);
    dbms_output.put_line(V_MESSAGE);
END;
/

SELECT EM.EMPLOYEE_ID, 
        EM.FIRST_NAME, 
        EM.LAST_NAME, 
        EM.EMAIL, 
        EM.PHONE_NUMBER, 
        EM.HIRE_DATE, 
        UTIL.GET_JOB_TITLE (P_EMPLOYEE_ID=>EM.EMPLOYEE_ID) AS JOB_TITLE,
        EM.SALARY, 
        EM.COMMISSION_PCT, 
        EM.MANAGER_ID, 
        UTIL.GET_DEP_NAME(P_EMPLOYEE_ID=>EM.EMPLOYEE_ID) AS DEPARTMENT_NAME
FROM ANDREW.EMPLOYEES EM;
    
    