create or replace TRIGGER HIRE_DATE_UPDATE 
    BEFORE UPDATE ON ANDREW.EMPLOYEES 
    FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    IF :OLD.JOB_ID!=:NEW.JOB_ID THEN
        :NEW.HIRE_DATE:=TRUNC(SYSDATE, 'DD');
    END IF;
--    COMMIT;
END HIRE_DATE_UPDATE;
/

ALTER TRIGGER HIRE_DATE_UPDATE DISABLE;
ALTER TRIGGER HIRE_DATE_UPDATE ENABLE;


UPDATE ANDREW.EMPLOYEES EM
SET EM.JOB_ID = 'SOME'
WHERE EM.EMPLOYEE_ID=102;

ROLLBACK;



